function setBasicTableCreateCmds(obj)
    obj.createSessionsTableCmd = ...
        ['CREATE TABLE sessions (' ...
        'sessionIDX int(11) NOT NULL AUTO_INCREMENT, ' ...
        'dateTime char(20), ' ...
        'customDir text, ' ...
        'simSpecFileDir varchar(400), ' ...
        'modelFileDir varchar(400), ' ...
        'simResultsDir varchar(400), ' ...
        'PRIMARY KEY (sessionIDX)) ENGINE=InnoDB'];
        
    obj.createMachinesTableCmd = ...
        ['CREATE TABLE machines (' ...
        'machineIDX int(11) NOT NULL AUTO_INCREMENT, ' ...
        'name char(100), ' ...
        'resourceType char(100), ' ...
        'PRIMARY KEY (machineIDX)) ENGINE=InnoDB'];
        
    obj.createSimulatorsTableCmd = ...
        ['CREATE TABLE simulators (' ...
        'simulatorIDX int(11) NOT NULL AUTO_INCREMENT, ' ...
        'machineIDX int(11) NOT NULL, ' ...
        'name char(200), ' ...
        'type char(200), ' ... 
        'version char(200), ' ...
        'FOREIGN KEY (machineIDX) REFERENCES machines(machineIDX), ' ...
        'PRIMARY KEY (simulatorIDX)) ENGINE=InnoDB'];
        
    obj.createExpDataSetsTableCmd = ...
        ['CREATE TABLE expDataSets (' ...
        'expDataSetIDX int(11) NOT NULL AUTO_INCREMENT, ' ... 
        'expSpecimenID int(11), ' ... 
        'expExperimentID int(11), ' ... 
        'samplingRate double, ' ...
        'expP1 char(100), ' ... 
        'expP2 double, ' ... 
        'expP3 double, ' ... 
        'expP4 double, ' ... 
        'expP5 double, ' ... 
        'expP6 double, ' ... 
        'expP7 double, ' ... 
        'PRIMARY KEY (expDataSetIDX)) ENGINE=InnoDB'];

    obj.createComparisonsTableCmd = ...
        ['CREATE TABLE comparisons (' ...
      'cmpIDX int(11) NOT NULL AUTO_INCREMENT, ' ...
      'runIDX int(11) NOT NULL, ' ...
      'cmpType char(100), ' ...
      'score1 double, ' ...
      'score2 double, ' ...
      'score3 double, ' ...
      'score4 double, ' ...
      'score5 double, ' ...
      'FOREIGN KEY (runIDX) REFERENCES simulationRuns(runIDX), ' ...
      'PRIMARY KEY (cmpIDX)) ENGINE=InnoDB'];
end
