function setIpvsTableCreateCmd(obj)
    % This version names all input parameters generically;
    % for better readability of accesses overriding would be helpful.
    % This assumes the number of input parameters is 21 but should
    % match that used by the NeuroManager constructor option
    % 'maxNumSimSpecParams'.  Note that we use all strings here.  This
    % is because we have no reason to do otherwise, and this actually
    % does match the NeuroManager SimSet.  However, doing searches and
    % joins on strings won't be very useful for parameters that are
    % numbers, so Subclass overrides will want to use numbers where
    % appropriate.  See the comparison table in this file and the
    % abiCompDB subclass for examples. 
    obj.createIpvsTableCmd = ...
        ['CREATE TABLE ipvs (' ...
        'ipvIDX int(11) NOT NULL AUTO_INCREMENT, ' ...
        'expDataSetIDX int(11) NOT NULL, ' ...
        'p01 char(20), ' ...
        'p02 char(20), ' ...
        'p03 char(20), ' ...
        'p04 char(20), ' ...
        'p05 char(20), ' ...
        'p06 char(20), ' ...
        'p07 char(20), ' ...
        'p08 char(20), ' ...
        'p09 char(20), ' ...
        'p10 char(20), ' ...
        'p11 char(20), ' ...
        'p12 char(20), ' ...
        'p13 char(20), ' ...
        'p14 char(20), ' ...
        'p15 char(20), ' ...
        'p16 char(20), ' ...
        'p17 char(20), ' ...
        'p18 char(20), ' ...
        'p19 char(20), ' ...
        'p20 char(20), ' ...
        'p21 char(20), ' ...
        'FOREIGN KEY (expDataSetIDX) REFERENCES expDataSets(expDataSetIDX), ' ...
        'PRIMARY KEY (ipvIDX)) ENGINE=InnoDB'];
end