function setSimFeatureExtractionsTableCreateCmd(obj)
    % This is for example and should be overridden
    obj.createSimFeatureExtractionsCmd = ...
        (['CREATE TABLE simFeatureExtractions (' ...
        'fxIDX int(11) NOT NULL AUTO_INCREMENT, ' ...
        'fxNumber double, ' ...
        'fxBool double, ' ...
        'PRIMARY KEY (fxIDX)) ENGINE=InnoDB']);
end