function setSimFeatureExtractionsCmd(obj)
    % Override the base class to define specific features
    obj.createSimFeatureExtractionsCmd = ...
        (['CREATE TABLE simFeatureExtractions (' ...
        'fxIDX int(11) NOT NULL AUTO_INCREMENT, ' ...
        'analysisStart double, ' ...
        'analysisDuration double, ' ...
        'stimulusStart double, ' ...
        'adaptation double, ' ...                      
        'avgFiringRate double, ' ...
        'avgHlfHgtWidth double, ' ...
        'baseV double, ' ...
        'maxSpkV double, ' ...
        'ISIFirst double, ' ...
        'ISIMean double, ' ...                             
        'ISICV double, ' ...                              
        'latency double, ' ...       
        'stimulusLatency double, ' ...
        'frstSpkThresholdV double, ' ...
        'hasSpikes bool, ' ...                         
        'numSpikes int(11), ' ...
        'hasBursts bool, ' ...
        'numBursts int(11), ' ...
        'maxBurstiness double, ' ...
        'hasPauses bool, ' ...
        'numPauses int(11), ' ...
        'pauseFraction double, ' ...
        'hasDelay bool, ' ...
        'delayRatio double, ' ...
        'delayTau double, ' ...
        'PRIMARY KEY (fxIDX)) ENGINE=InnoDB']);
end
