% NEURONSLURMCluster
% Ignores wall clock time
classdef NEURONSLURMCluster < SLURMCluster & NeuronMachine
    methods
        function obj = NEURONSLURMCluster(wallClockTime,...
                                   hostID, hostOS, ~, ~, ...
                                   baseDir, scratchDir,...
                                   simFileSourceDir, custFileSourceDir,...
                                   modelFileSourceDir,...
                                   simType, numSims,...
                                   xCompilationMachine,...
                                   xCompilationScratchDir,...
                                   auth, log, notificationSet, dataFunc,...
                                   queueData, ~, ~, numNodes)
            md = dataFunc();
            obj = obj@NeuronMachine(md);

            obj = obj@SLURMCluster(wallClockTime,...
                                   hostID, hostOS, '', '',...
                                   baseDir, scratchDir,...
                                   simFileSourceDir, custFileSourceDir,...
                                   modelFileSourceDir,...
                                   simType, numSims,...
                                   xCompilationMachine,...
                                   xCompilationScratchDir,...
                                   auth, log, notificationSet, dataFunc,...
                                   queueData, '', '', numNodes);
         end
        
        % ----------
        % Neuron model processing is machine-dependent. On CBI we compile
        % the model files as part of the job submission, not here.
        % This is called from SimNeuron.
        % Refer to NeuroManagerStaging.xlsx
        function str = getCompileNeuronModelFilesStrPhaseP(obj, simulation) %#ok<INUSD>
            str = '';  
        end
        
        % ----------
        % Neuron model processing is machine-dependent. On CBI we compile
        % the model files as part of the job submission, which is here.
        % This is called from SimNeuron.
        % Refer to NeuroManagerStaging.xlsx
        function str = getCompileNeuronModelFilesStrPhaseD(obj, simulation) 
            str = obj.getModelFileCompileStr(simulation);
        end
        
        % ----------
        % Override the job file here if you like
        %function jobfilename = PreRunCreateJobFile(obj, scratchdir, jobroot, remoterundir, runcommand)
            % ...
        %end
    end
    
    %     methods (Access=protected)        
%     % CreateDownloadExpectFile.m
%     % Can be overridden here for localization.
% %     function CreateDownloadExpectFile(obj, hostdir, targetpath)
% %         ...
% %     end
%     end

end
