%
classdef abiMMCompDB < abiCompDB
    methods (Access=protected)
        setIpvsTableCmd(obj)
    end
    
    methods 
        function obj = abiMMCompDB(dataSourceName, databaseName, ...
                                     userName, password)
            obj = obj@abiCompDB(dataSourceName, databaseName, ...
                                userName, password);
            obj.setIpvsTableCmd(); % subclass--specific
        end

        %% addIPV 
        % An override of the abiCompDB method for further specialization.
        function ipvIndex = ...
                    addIPV(obj, expDataSetIndex, ...
                           curr, vinit, delay, stimdur, ...
						   tstep, tstop, rcdintvl, ...
						   Kh_soma, Kh_smooth, Kh_spiny, ...
                           CaE_soma, CaE_smooth, CaE_spiny, ...
						   KD_soma, KD_smooth, KD_spiny, ...
                           ~, ~, ~, ~, ~)
            colnames = {'ipvIDX', 'expDataSetIDX', ...
						'curr', 'vinit', 'delay', 'stimdur', ...
						'tstep', 'tstop', 'rcdintvl', ...
						'Kh_soma', 'Kh_smooth', 'Kh_spiny', ...
						'CaE_soma', 'CaE_smooth', 'CaE_spiny', ...
						'KD_soma', 'KD_smooth', 'KD_spiny', ...
						'p17', 'p18', 'p19', 'p20', 'p21'};

			% p17-p21 are not used here
			p17Str = 'NULL';
			p18Str = 'NULL';
			p19Str = 'NULL';
			p20Str = 'NULL';
			p21Str = 'NULL';  
			
            %%
            coldata = ...
               {num2str(expDataSetIndex), ...
			    num2str(curr), num2str(vinit), num2str(delay), num2str(stimdur), ...
			    num2str(tstep), num2str(tstop), num2str(rcdintvl), ...
 			    num2str(Kh_soma), num2str(Kh_smooth), num2str(Kh_spiny), ... 
			    num2str(CaE_soma), num2str(CaE_smooth), num2str(CaE_spiny), ...
			    num2str(KD_soma), num2str(KD_smooth), num2str(KD_spiny), ...
                p17Str, p18Str, p19Str, p20Str, p21Str};
            insertStr = ['insert into ipvs (' ...
                         strjoin(colnames, ', ') ') values(0, ' ...
                         strjoin(coldata, ', ') ')'];
            curs = exec(obj.dbConn, insertStr);
            curs = fetch(curs);
            close(curs);
            
            q = ('select ipvIDX from ipvs WHERE ipvIDX = @@IDENTITY');
            curs = exec(obj.dbConn, q);
            curs = fetch(curs);
            ipvIndex = curs.Data.ipvIDX;
            close(curs);
        end
    end
end