function setIpvsTableCmd(obj)
    % Override the base class to name many input parameters for clarity
    obj.createIpvsTableCmd = ['CREATE TABLE ipvs (' ...
        'ipvIDX int(11) NOT NULL AUTO_INCREMENT, ' ...
        'expDataSetIDX int(11) NOT NULL, ' ...
        'tstop double, ' ...
        'tstep double, ' ... 
        'taum double, ' ...
        'refrac double, ' ...
        'alpha double, ' ...
        'rM double, ' ...
        'vRest double, ' ...
        'thresholdHeight double, ' ...
        'spikeHeight double, ' ...
        'rsrv double, ' ...
        'stimulusType char(100), ' ...
        'sC01 double, ' ...
        'stimulusStartTime double, ' ...
        'pulseWidth double, ' ...
        'pulseCurrent double, ' ...
        'sC05 double, ' ...
        'sC06 double, ' ...
        'sC07 double, ' ...
        'sC08 double, ' ...
        'sC09 double, ' ...
        'sC10 double, ' ...
        'FOREIGN KEY (expDataSetIDX) REFERENCES expDataSets(expDataSetIDX), ' ...
        'PRIMARY KEY (ipvIDX)) ENGINE=InnoDB'];
end
