function setSimFeatureExtractionsCmd(obj)
    % Override the base class to define specific features
    obj.createSimFeatureExtractionsCmd = ...
        (['CREATE TABLE simFeatureExtractions (' ...
        'fxIDX int(11) NOT NULL AUTO_INCREMENT, ' ...
        'analysisStart double, ' ...
        'analysisDuration double, ' ...
        'adaptation double, ' ...                      
        'avgFiringRate double, ' ...
        'hasSpikes bool, ' ...                         
        'numSpikes int(11), ' ...
        'hasBursts bool, ' ...
        'numBursts int(11), ' ...
        'maxBurstiness double, ' ...
        'hasPauses bool, ' ...
        'numPauses int(11), ' ...
        'pauseFraction double, ' ...
        'delayRatio double, ' ...
        'delayTau double, ' ...
        'first_isi double, ' ...
        'mean_isi double, ' ...                             
        'isi_cv double, ' ...                              
        'f_peak double, ' ...  
        'latency double, ' ...       
        'stimulusLatency double, ' ...
        'threshold double, ' ...
        'PRIMARY KEY (fxIDX)) ENGINE=InnoDB']);
end
