classdef MMInvDBSimSpecFile < SimSpecFile
    properties
    end
    methods
        function obj = MMInvDBSimSpecFile(path, simSetID, filename)
            obj = obj@SimSpecFile(path, simSetID, ...
                                  filename, SimType.SIM_MMINVDB);
            obj.paramNameStr = ...
                ['curr vinit delay stimdur tstep tstop rcdintvl ' ...
                 'Kh_soma Kh_smooth Kh_spiny ' ...
                 'CaE_soma CaE_smooth CaE_spiny ' ...
                 'KD_soma KD_smooth KD_spiny ' ...
                 'p17 p18 p19 p20 p21'];
        end
    end
end