function setIpvsTableCmd(obj)
    % Override the base class to name many input parameters for clarity
    obj.createIpvsTableCmd = ['CREATE TABLE ipvs (' ...
        'ipvIDX int(11) NOT NULL AUTO_INCREMENT, ' ...
        'expDataSetIDX int(11) NOT NULL, ' ...
        'tstop double, ' ...
        'tstep double, ' ... 
        'taum double, ' ...
        'refrac double, ' ...
        'alpha double, ' ...
        'rM double, ' ...
        'vRest double, ' ...
        'thresholdHeight double, ' ...
        'spikeHeight double, ' ...
        'p10 double, ' ...
        'stimulusType char(100), ' ...
        'p12 double, ' ...
        'stimulusStartTime double, ' ...
        'pulseWidth double, ' ...
        'pulseCurrent double, ' ...
        'p16 double, ' ...
        'p17 double, ' ...
        'p18 double, ' ...
        'p19 double, ' ...
        'p20 double, ' ...
        'p21 double, ' ...
        'FOREIGN KEY (expDataSetIDX) REFERENCES expDataSets(expDataSetIDX), ' ...
        'PRIMARY KEY (ipvIDX)) ENGINE=InnoDB'];
end
