% extractABIExpFeatures
function [status, cmdout] = ...
         extractABIExpFeatures(simID, ...
                               timeFilename, ...
                               voltageFilename, ...
                               stimulusFilename, ...
                               simDuration, ...        
                               stimStart, ...          
                               stimDuration, ...       
                               analysisStart, ...      
                               analysisDuration, ...   
                               featuresFilename, ...
                               runDir, ...
                               outDir ...
                               ) %#ok<*INUSD>

	% Get the proper SimCore configuration
    % To avoid rewriting the interface of runPythonSimulation at this time,
    % we redo the finding of the simCore here.
    load('MachineData.dat', 'remoteConfig', '-mat');
    simCore = {};
    for i = 1:length(remoteConfig.simCores)
        if strcmp(remoteConfig.simCores{1,i}.name, remoteConfig.assignedSimCoreName)
            simCore = remoteConfig.simCores{1,i};
        end
    end
    if isempty(simCore)
        % Deal with errors here and in the rest of the file 
        % (not implemented yet)
    end
                           
    cd(runDir);
    pyStr = [simCore.config.abiPythonPath, ' ' ...
             fullfile(runDir, 'STGFeatExtr.py') ' ' ...
             simID ' ' ...
             timeFilename ' ' ...
             voltageFilename ' ' ...
             stimulusFilename ' ' ...
             num2str(simDuration) ' ' ...
             num2str(stimStart) ' ' ...
             num2str(stimDuration) ' ' ...
             num2str(analysisStart) ' ' ...
             num2str(analysisDuration) ' ' ...
             featuresFilename ' ' ...
             outDir ' ' ...
              '1> ' fullfile(outDir, 'FXout.txt') ...
             ' 2> ' fullfile(outDir, 'FXerr.txt')];
    [status, cmdout] = system(pyStr);
end